### ISSUE TITLE
Test support for localhost client

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#1105]
IBC-Go team to upstream localhost client to main stream repo. 

The Relayer should support this feature.
localhost client is being developed in this branch:

https://github.com/cosmos/ibc-go/tree/09-localhost

**Comment by jtieri** [comment]
There has also been a slight change to localhost ibc that introduces a 1 byte sentinel proof which should be provided in the proof field of messages, otherwise localhost state verification will fail. 

https://github.com/cosmos/ibc-go/pull/3195
https://github.com/cosmos/ibc-go/blob/09-localhost/modules/light-clients/09-localhost/keys.go#L12

**Comment by jonathanpberger** [comment]
@jtieri pls find time to pair w/ @agouin on this

**Comment by jtieri** [comment]
Update: Andrew and I paired on this and finally got past our blockers around the channel handshake. I started to test ics-20 transfers but cmd for executing a transfer always fails with the following error

```
send ibc transfer: exit code 1:  Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = client-id: 09-localhost: consensus state not found: key not found
```

I did some debugging over the weekend and I don't think this is an issue on our side so I have opened an issue in the ibc-go repo.

See issue [here](https://github.com/cosmos/ibc-go/issues/3568)

**Comment by jonathanpberger** [comment]
@jtieri pls tag ppl to get reviews on the PR :-)
