### ISSUE TITLE
Constant `unknown type \"tendermint.crypto.PublicKey_Ed25519\""` errros

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#1354]
I believe this was introduced with #1312 

```
 "error": "error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). error unmarshalling result: unknown type \"tendermint.crypto.PublicKey_Ed25519\""
```

**Comment by jtieri** [comment]
possibly a result of introducing a forked version of `CometBFT` in order to solve #1273?

looks like `CometBFT` has a `v1.x.x` stable release slated for the end of this year, see their [project board](https://github.com/orgs/cometbft/projects/1/views/20) (an alpha release was recently tagged [here](https://github.com/cometbft/cometbft/releases/tag/v1.0.0-alpha.1))

if this issue is indeed an artifact of introducing our forked repo then perhaps this issue will be solved by removing the forked repo as a dependency and importing two different versions of the upstream repo to account for the API breaking changes introduced to `ResultBlockResults` across v0.34.X [Block Results RPC](https://github.com/cometbft/cometbft/blob/v0.34.29/rpc/core/types/responses.go#L49) and v0.38.X [Block Results RPC](https://github.com/cometbft/cometbft/blob/v0.38.0-rc3/rpc/core/types/responses.go)
