### ISSUE TITLE
2.5.1 error messages

### ISSUE THREAD

**Issue by PFC-developer** [cosmos/relayer#1427]
is there a way to get the chain id's into the error messages ?

specifically
```
 2024-03-14T12:58:36.967438Z    warn    Flush not complete    {"error": "failed to enqueue pending messages for flush: no ibc messages found for send_packet query: send_packet.packet_src_channel='channel-18' AND send_packet.packet_sequence='388'"}
```

**Comment by jtieri** [comment]
Good call out @PFC-developer! 

I [opened a PR](https://github.com/cosmos/relayer/pull/1428) that adds both chain IDs and the client IDs to the log statement, this should be much more useful when trying to debug an incomplete flush. If there are any other areas where we could improve logs for operators please feel free to open more issues 🙂

**Comment by parveenkaushikmajra** [comment]
@PFC-developer @jtieri I am having the same error during ibc relayer on version 2.4.1. How can I resolve this?Should I need to update it to v 2.5.1?
`warn        Flush not complete        {"error": "flush was successful, but packets are still pending. { src_chain-id channel-0 transfer recv: 0, ack: 35 } "}`

**Comment by jtieri** [comment]
> @PFC-developer @jtieri I am having the same error during ibc relayer on version 2.4.1. How can I resolve this?Should I need to update it to v 2.5.1? `warn Flush not complete {"error": "flush was successful, but packets are still pending. { src_chain-id channel-0 transfer recv: 0, ack: 35 } "}`

This log doesn't appear to be problematic on its own. The relayer has a limit on the size of the txs that it will broadcast which means there is a limit on the number of msgs that it attempts to batch. The log you shared just means that during a periodic flush the relayer was able to relay some number of IBC related msgs successfully but that it didn't fully clear the queue of pending packets due to this hardcoded limit on tx size.
