### ISSUE TITLE
Audit and refactor all the `rly path` commands

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer#280]
- [ ] `list` - currently the status on the list is broken
- [ ] `show` - currently the status is broken
- [ ] `add` - Validation issues around version and ordering
- [ ] `generate` - Broken in a number of places, especially looking at existing primitives on chain.
- [x] `delete`

**Comment by jackzampolin** [comment]
Also see https://github.com/ovrclk/relayer/issues/162

**Comment by akhilkumarpilli** [comment]
@jackzampolin, `status` on the list is broking because we are querying client state with latest height [here](https://github.com/cosmos/relayer/blob/031ecc2e304af39c789acd0f1b84033d3b8ef4d2/relayer/path.go#L244). We are getting error: `proof is unexpectedly empty; ensure height has not been pruned: invalid request` sometimes because client data is not yet stored with latest height. We can fix this issue with querying client state with height equal to `latestHeight-1`. Is it okay to pass `latestHeight-1`?

**Comment by jackzampolin** [comment]
Pretty sure these are still borked and could use some love. Good first issue
