### ISSUE TITLE
How to display IBC denominations?

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer#288]
There is currently some debate about how to display the IBC denominations. One option is to display the channel/port/denom data. This is confusing to end users. [CAIPs](https://github.com/ChainAgnostic/CAIPs) have been developed by the IOV team to address this exact problem. I also know @michaelfig and the Agoric team have opinions here. I tried disambiguating the denom to a style similar to CAIPs and ran into a couple of issues. That code is reproduced below:

```go
dts, err := chain.QueryDenomTraces(0, 1000, h)
if err != nil {
	return err
}

out := sdk.Coins{}
for _, c := range coins {
	if len(dts.DenomTraces) > 0 {
		for _, d := range dts.DenomTraces {
			switch {
			// We are seeing an IBC denom with no coins in it don't display this to the user
			case c.Amount.Equal(sdk.NewInt(0)):
			// We are seeing an IBC denom with no coins, look up client state from channel info
			// and set denom according to https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-19.md
			// NOTE: Currently denom parsing prohibits this. We should discuss this in more detail
			case c.Denom == d.IBCDenom():
				// Split the path
				// NOTE: We should upstream some functions to deal with IBC denoms into the SDK
				sp := strings.Split(d.Path, "/")
				// Set channel and port info on path for query
				if err := chain.AddPath(scid, sconnid, sp[len(sp)-1], sp[len(sp)-2], order); err != nil {
					return err
				}
				// Query the client state from the channel information
				// NOTE: This should return something that I can use `UnpackClientState` to unmarshall
				// but it doesn't
				ccr, err := chain.QueryChannelClient(h)
				if err != nil {
					return err
				}
				// Set client info on path for query
				if err := chain.AddPath(ccr.IdentifiedClientState.ClientId, sconnid, schanid, sportid, order); err != nil {
					return err
				}
				// Query the state of the client
				csr, err := chain.QueryClientState(h)
				if err != nil {
					return err
				}
				// Unpack it into the concrete type
				cs, err := clienttypes.UnpackClientState(csr.GetClientState())
				if err != nil {
					return err
				}
				// Handle denom differently depending on client type
				switch csType := cs.(type) {
				case *tmclient.ClientState:
					out = append(out, sdk.NewCoin(fmt.Sprintf("tendermint/%s/%s", csType.ChainId, d.GetBaseDenom()), c.Amount))
				case *lhclient.ClientState:
					out = append(out, sdk.NewCoin(fmt.Sprintf("localhost/%s/%s", csType.ChainId, d.GetBaseDenom()), c.Amount))
				case *smclient.ClientState:
					out = append(out, sdk.NewCoin(fmt.Sprintf("solomachine/%s", d.GetBaseDenom()), c.Amount))
				default:
					return fmt.Errorf("client type %T not supported", csType)
				}
			default:
				out = append(out, c)
			}
		}
	} else {
		out = coins
	}
}
```

**Comment by michaelfig** [comment]
> I also know @michaelfig and the Agoric team have opinions here.

Not sure what I think, but @warner and @dtribble may weigh in.

**Comment by colin-axner** [comment]
If I am a user interacting with an asset I have a few initial questions:
* What chain is this from and what is the name of the asset?
* Is this a native asset or has this asset traveled across the universe via IBC?
* Is this asset "certified" by the service I am using?

In my ideal interaction (let's say exchanges who fulfill the IBC competency matrix) when displayed an asset it looks something like the following:
`<chain-id>:<native>|<IBC>:<baseDenomination>` 

If the asset is IBC, there would likely be a hash in smaller text or italics of the IBC path + base denom as specified in ICS20. There would also be a way to expand the asset to see the full history of the IBC asset. There could be some sort of check mark or green text to indicate that this asset, is a supported native asset or it has traveled through the proper ports/channels to arrive to this chain. 

Displaying the client type is unnecessary because it has no effect on the value of the token since this is the type of the counterparty. Displaying the clientID is unnecessary because it can be implied by the port/channel. A specific port/channel can only refer to a certain client. We also need more than just the most recent travel path since two assets arriving via the same port/channel can be significantly different. 

For example:
I send atoms from the hub to chainB.
I mint atoms on chainA and send them to chainB.

I send both the ibc assets on chainB to chainC.

From chainC, both assets came from chainB via the same client and have the same base denom, "atoms". The important difference is the history of the hop one before, when they were sent to chainB. For this reason, the entire history must always be accessible to the user. 

I don't think most users will actually want to see the full history, which is why I think the ideal use case minimizes this information. While the hash is meant for internal chain usage and may not even be used by all chains implementing ICS20, I think it can be useful as a quick reference for uniqueness. Initially I was hesitant to show hashes to users since this is meant for internal representation, but I think most users are somewhat used to hashes by now. 

I think this question can almost be redirected to: how do the most widely used/accepted IBC paths look.

Certainly there will be a set of widely agreed upon IBC paths. Coins that travel from the hub to Agroic, or Ethereum to the hub etc. Services will likely want to shorten these and avoid displaying paths/hashes and instead use the UI to show that this coin is a certified token.Eth transferred to the hub via "accepted" paths would be represented as:

`cosmos-hub:IBC:Eth` 

with a green text or a check mark or something indicating certification. You could drop the hash **only if** it is the only certified eth to hub path or it is considered equivalent to all other eth to hub paths by this exchange. The full path should still be accessible, just minimized.

I cannot imagine any way of shortening non-certified token, aside from using hashes. The full path is necessary for truly understanding the asset you are interacting with

This is just my 2 satoshis.

**Comment by jackzampolin** [comment]
closing this in favor of other discussions elsewhere.
