### ISSUE TITLE
Understanding Verifying process for cross-chain Transaction.

### ISSUE THREAD

**Issue by himankgupta31** [cosmos/relayer#338]
Hello @colin-axner 

I want to know the process of validation in Cross-Chain Transaction. 

I have development scenario in our local Machine as follows:

COSMOS-Chian-A (COSMOS-SDK: Stargate Commit) <-> Relayer <-> COSMOS-Chian-B (COSMOS-SDK: Stargate Commit).

According to my current understanding, IBC generate light client on cross chain. E.g., For chain A, IBC generate light client at Chain B. But I am assuming that both the chains are using same properties of Tendermint Consensus Algorithm. And IBC uses Merkle Tree Proof for validating cross chain transaction. (Please correct if I am wrong). I want to know which part of code in IBC taking care of verifying process? 

I also want to know if we modify the Tendermint consensus algorithm for one of the chain then also cross-chain validation will work in same manner?
If I have 4-5 chains (IBC enabled) connecting through Gaia, so in each chain I have to create light client for every other chain for verifying the cross chain transaction. 

Any hint will be great help for me as I am currently understanding the IBC code in depth for future development and contributions. 

Regards
Himank Gupta

**Comment by colin-axner** [comment]
Howdy! @himankgupta31 

> According to my current understanding, IBC generate light client on cross chain. E.g., For chain A, IBC generate light client at Chain B. But I am assuming that both the chains are using same properties of Tendermint Consensus Algorithm. 

Each chain will need to create an on-chain light client which processes proofs of the counterparty chain it wants to connect to. To make things easier on the relayer, an off-chain light client is also created to track the counterparty chains. 

> And IBC uses Merkle Tree Proof for validating cross chain transaction. 

IBC doesn't necessarily use merkle proofs. The IBC tendermint light client does use merkle proofs because that is how tendermint has chosen to construct their proofs. The IBC tendermint light client makes calls to the light client code implemented in the tendermint repo to verify proofs that it receives. Other light clients implemented for IBC can use any format they wish. For example, the solo machine simply verifies signatures. 

> I want to know which part of code in IBC taking care of verifying process?

What you are probably looking for is the IBC tendermint [verify functions](https://github.com/cosmos/cosmos-sdk/blob/7c1da3d9988c361d6165d26d33bed47352072366/x/ibc/light-clients/07-tendermint/types/client_state.go#L157)

> I also want to know if we modify the Tendermint consensus algorithm for one of the chain then also cross-chain validation will work in same manner?

So long as you don't break the block, proof format, or security model, then I believe it should be fine. However, I am not a qualified Tendermint expert. If you modify Tendermint and want to deploy the modified chain with IBC enabled, I highly recommend you consult the Tendermint team to ensure the security model has not been broken. If you want to just use it for testing, then it will most likely be fine. 

> If I have 4-5 chains (IBC enabled) connecting through Gaia, so in each chain I have to create light client for every other chain for verifying the cross chain transaction.

Correct to a degree. If you use a hub as an intermediary then you can have all the zones create a client for the hub, and the hub create a client for each zone. Then you can go zoneA -> hub -> zoneB

> Any hint will be great help for me as I am currently understanding the IBC code in depth for future development and contributions.

Checkout our [docs](https://docs.cosmos.network/master/modules/ibc/#)! Also, join the discord linked in the SDK repo. Community forums are better formats for asking questions. Github issues should be reserved for bugs/feature requests to avoid noise for core developers

**Comment by himankgupta31** [comment]
@colin-axner Thank you very much for great explanation. 

I tried to post on discord but I did not get any satisfactory answer as I get here. So I just mention you in the post as I am assuming that you are having end-to-end clarification on IBC.

Once again thank you very much for your help.
