### ISSUE TITLE
licensing: is this code licensed to Cosmos Authors or to Jack and if so clarity

### ISSUE THREAD

**Issue by odeke-em** [cosmos/relayer#343]
This isn’t my domain of work, but I noticed that this code bears a license with ownership
https://github.com/cosmos/relayer/blob/031ecc2e304af39c789acd0f1b84033d3b8ef4d2/main.go#L2

Which begs the question of ownership and copyright. Did the licensing change when this code was added/moved here or is it donated to the Cosmos ecosystem with the condition that the license stays as is? A clarification would be useful. Thank you!

**Comment by anilcse** [comment]
cc @jackzampolin

**Comment by colin-axner** [comment]
cc @cwgoes @okwme

**Comment by ebuchman** [comment]
Code is copyrighted by its authors. Everyone who has contributed code to this repo owns the copyright for the code they contributed.

Jack as the original author owned the original copyright and licensed the code under Apache. Which means everyone else who contributed (and owns copyright) also licensed under Apache.

Technically speaking we could/should change the copyright statement to something like "copyright cosmos relayer authors" and refer to the contributors list, since I doubt any of the other contributors have assigned their ownership to Jack.

We could also ask Jack and/or others if they're willing to assign they're copyright to Interchain GmbH, who is taking over maintenance, but technically it's not really necessary, especially as they will build up their own ownership claims through additional contributions.

**Comment by jackzampolin** [comment]
Strangelove Ventures can take this
