### ISSUE TITLE
Support multiple sender keys for a single chain

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#403]
Chains currently use a single key to sign messages. This requires editing the config to use a different sender key. I don't think adding another config will work since the chain-id would already exist.

The code heavily relies on the existence of a single key. Adding multiple keys might be easy, but it will lead to more instability/bugs in the code. I don't think this feature should be added without a comprehensive pr which simplifies the existing code. I am open to proposals. It might be easier to fix than I think, but what I'd like to avoid is passing a key down from the command CLI calls into the relayer/ code and throughout all the functions. 

A short term workaround is to use the `gaiad tx ibc-transfer transfer` command. The downside is the key used here will need to be added to the gaiad keystore as well and the relayer will still need to be run. I'd recommend wallets/exchanges to implement their own client side code for initiating a transfer and only using the relayer to relay messages. Regular users should not be executing relayer code

**Comment by jackzampolin** [comment]
This would be a cool feature but I agree it would be complex to implement. Would also need to implement and easy way to fund all those wallets so they could pay fees. I'm thinking this work wouldn't be worth it but 🤷‍♂️ if someone wants to take a stab we will review PRs

**Comment by boojamya** [comment]
Updated issue/idea created here:
https://github.com/cosmos/relayer/issues/839

**Comment by dylanschultzie** [comment]
@boojamya @jackzampolin 

I disagree with how this issue has been updated/resolved - this would be an absurdly helpful feature for relayers. Right now we manage multiple relaying "hubs" with a different wallet each in order to optimize against `Account Sequence Mismatch` errors.

Having the ability to have a multitude of wallets on a single hub would be a *godsend*. I know many other relayers use the same system we do, and I'd bet they'd also utilize this feature heavily.

Meaning: I think this issue should remain open so others are aware it's desired.
