### ISSUE TITLE
Transfers are failing on different account-prefix chains

### ISSUE THREAD

**Issue by anilcse** [cosmos/relayer#43]
Transfers are not going through between chains with different account-prefix's
Here is the log:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xead32c]

goroutine 1 [running]:
github.com/iqlusioninc/relayer/relayer.(*Chain).CreateConnectionStep(0xc000d57560, 0xc000d57320, 0x0, 0x0, 0x7f0760e8a2d8)
 /home/sys-597/go/src/github.com/iqlusioninc/relayer/relayer/tx.go:153 +0x93c
github.com/iqlusioninc/relayer/relayer.(*Chain).CreateConnection(0xc000d57560, 0xc000d57320, 0x2540be400, 0xd, 0xc000df6090)
 /home/sys-597/go/src/github.com/iqlusioninc/relayer/relayer/tx.go:75 +0x84
github.com/iqlusioninc/relayer/cmd.fullPathCmd.func1(0xc000d13600, 0xc000d23780, 0x2, 0x2, 0x0, 0x0)
 /home/sys-597/go/src/github.com/iqlusioninc/relayer/cmd/tx.go:180 +0x384
github.com/spf13/cobra.(*Command).execute(0xc000d13600, 0xc000d23700, 0x2, 0x2, 0xc000d13600, 0xc000d23700)
 /home/sys-597/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x1f65620, 0x43f13a, 0x1efa600, 0xc000000180)
 /home/sys-597/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
 /home/sys-597/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
github.com/iqlusioninc/relayer/cmd.Execute()
 /home/sys-597/go/src/github.com/iqlusioninc/relayer/cmd/root.go:97 +0x55
main.main()
 /home/sys-597/go/src/github.com/iqlusioninc/relayer/main.go:21 +0x20
```

Looks like the client connection is failing and `QueryClientState` returning empty state for second chain

**Comment by kwunyeung** [comment]
When I tested the path, it returned this error.

```
E[2020-03-22|16:57:49.686] - [morpheus-ibc-3000] -> err(failed to unmarshal JSON bytes: invalid Bech32 prefix; expected desmos, got cosmos) 
```

**Comment by anilcse** [comment]
Looks like the issue is here: https://github.com/iqlusioninc/relayer/blob/master/relayer/chain.go#L144-L149

**Comment by RiccardoM** [comment]
This seems to be a lot more complex than it looks like. 

The actual problem lies inside the Cosmos SDK code, and the fact that it uses a singleton `SdkConfig` object that contains the account prefixes. 

Now, let's assume you have two different chain codebases: 

1. Chain A has account prefix `alice` 
2. Chain B has account prefix `bob` 

In order to send some tokens from chain A to chain B, the following steps need to be performed: 

1. On Chain A, a `MsgTransfer` is created, signed and sent.
2. On Chain A, the `MsgTransfer` triggers the creation of a `FungibleTokenPacketData` object, which is itself signed. 
3. On Chain B, a `MsgReceivePacket` is created, signed and sent. 
4. On Chain B, the reception of a `MsgReceivePacket` triggers the reading of a `FungibleTokenPacketData` and its verification. 

Now, here's the catch.

Inside step **2**, while **signing** the `FungibleTokenPacketData` object, the `GetBytes()` method serializes the object as follows (omitting non-important data): 

```json
{
  "sender": "alice156yhr0xqfvgdg56sck8mz593x9zm72u37euyu6",
  "receiver": "alice1xnfs7newj2j3e8ynkmcjentyh06w9s6wj0nknt",
}
```

leading to the creation of a specific signature, let's call it `sigA`. 

On the other hand, inside step **4**, while **verifying** the packet, the `GetBytes()` method seralizes the object as follows (again, omitting non-important data): 

```json
{
  "sender": "bob156yhr0xqfvgdg56sck8mz593x9zm72u37euyu6",
  "receiver": "bob1xnfs7newj2j3e8ynkmcjentyh06w9s6wj0nknt",
}
```

which leads to the creation of a **different** signature (`sigB`) and the return of a `unauthorized` error.

Now, why is that? 

It's pretty straightforward looking at how the `sdk.AccAddress` is serialized:

```golang
// MarshalJSON marshals to JSON using Bech32.
func (aa AccAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(aa.String())
}

// String implements the Stringer interface.
func (aa AccAddress) String() string {
	if aa.Empty() {
		return ""
	}

	bech32PrefixAccAddr := GetConfig().GetBech32AccountAddrPrefix()

	bech32Addr, err := bech32.ConvertAndEncode(bech32PrefixAccAddr, aa.Bytes())
	if err != nil {
		panic(err)
	}

	return bech32Addr
}
```

As you can see, while serializing an address, the Bech32 prefix that is used is the one set inside the singleton `Config` object, which **cannot be changed once the code is compiled**. 

Thus, if you use two different chains code (the first having Bech32 prefix `alice` and the second one having Bech32 prefix `bob`) there is no way this can work unless you change the code to force the usage of the respective account prefix while serializing a `FungibleTokenPacketData` instance.

**Comment by rmontagnin** [comment]
This seems to be a lot more complex than it looks like.

The actual problem lies inside the Cosmos SDK code, and the fact that it uses a singleton SdkConfig object that contains the account prefixes.

Now, let's assume you have two different chain codebases:

- Chain A has account prefix `alice`
- Chain B has account prefix `bob`

In order to send some tokens from chain A to chain B, the following steps need to be performed:

1. On Chain A, a `MsgTransfer` is created, signed and sent.
2. On Chain A, the `MsgTransfer` triggers the creation of a `FungibleTokenPacketData` object, which is itself signed.
3. On Chain B, a `MsgReceivePacket` is created, signed and sent.
4. On Chain B, the reception of a `MsgReceivePacket` triggers the reading of a `FungibleTokenPacketData` and its verification.

Now, here's the catch.

Inside step 2, while **signing** the `FungibleTokenPacketData` object, the `GetBytes()` method serializes the object as follows (omitting non-important data):

```json
{ 
  "sender": "alice156yhr0xqfvgdg56sck8mz593x9zm72u37euyu6", 
  "receiver": "alice1xnfs7newj2j3e8ynkmcjentyh06w9s6wj0nknt" 
}
```

leading to the creation of a specific signature, let's call it `sigA`.

On the other hand, inside step 4, while **verifying** the packet, the `GetBytes()` method serializes the object as follows (again, omitting non-important data):

```json
{
  "sender": "bob156yhr0xqfvgdg56sck8mz593x9zm72u37euyu6", 
  "receiver": "bob1xnfs7newj2j3e8ynkmcjentyh06w9s6wj0nknt"
}
```

which leads to the creation of a different signature (`sigB`) and the return of a unauthorized error.

Now, why is that?

It's pretty straightforward looking at how the sdk.AccAddress is serialized:

```golang
// MarshalJSON marshals to JSON using Bech32. 
func (aa AccAddress) MarshalJSON() ([]byte, error) {  
    return json.Marshal(aa.String()) 
} 

// String implements the Stringer interface. 
func (aa AccAddress) String() string {  
    if aa.Empty() {   
        return ""  
    }  

    bech32PrefixAccAddr := GetConfig().GetBech32AccountAddrPrefix()  
    bech32Addr, err := bech32.ConvertAndEncode(bech32PrefixAccAddr, aa.Bytes())  
    if err != nil {
       panic(err)  
    }  

    return bech32Addr 
}
```

As you can see, while serializing an address, the Bech32 prefix that is used is the one set inside the singleton `Config` object, which cannot be changed once the code is compiled.

Thus, if you use two different chains code (the first having Bech32 prefix `alice` and the second one having Bech32 prefix `bob`) there is no way this can work unless you change the code to force the usage of the respective account prefix while serializing a `FungibleTokenPacketData` instance.

**Comment by cwgoes** [comment]
@zmanian suggests `sdk.ForeignAddress` with prefix included in the address type.

Also we need to check the prefixes associated with a given channel, since they should be fixed (for a particular chain on the other end).

**Comment by cwgoes** [comment]
Alternatively we could just change the type to a new-typed string (duh?).

**Comment by jackzampolin** [comment]
I've opened an issue on the sdk for this work: https://github.com/cosmos/cosmos-sdk/issues/5977

**Comment by jackzampolin** [comment]
Pretty sure this is resolved by @cwgoes work.
