### ISSUE TITLE
Add documentation for timeout threshold

### ISSUE THREAD

**Issue by orkunkl** [cosmos/relayer#433]
I have been tinkering with relayer lately. There is an issue that I don't understand, and under documented.
- What is `trusting-period` and what `--timeout-threshold`'s relation with it? 
- How to configure these values to achieve a long living relayer?

**Comment by colin-axner** [comment]
Yes documentation for this would be great. `trusting-period` is a tendermint specific concept. When we create an on-chain IBC light client representing a tendermint chain (for example, the cosmos hub), we need to specify the period of time it can be trusted to validate headers between. This relates to the unbonding period. The unbonding period is the mechanism that holds validators accountable while they transition from leaving the validator set. The trusting period must be less than the unbonding period

If the trusting period + the last update consensus state timestamp (last header the on chain client was updated with) is past the current time, the on-chain IBC client has become "expired" and can no longer be updated (since it is unsafe, per the tendermint light client security model). If the time to expiry is within the `timeout-threshold`, then we want to update the client to prevent it from becoming expired. In general we don't want to update the client frequently since it is just extra gas cost for no benefits. I think we could rename `--timeout-threshold` but I'm not sure what is an intuitive flag name

cc @akhilkumarpilli

**Comment by colin-axner** [comment]
To close this issue:
- ensure timeout threshold is well documented
