### ISSUE TITLE
Rly Start -> update client error

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#581]
`I[2022-02-16|13:29:16.997] - [juno-1]<->[osmosis-1] - try(1/5) updating clients from chains: rpc error: code = InvalidArgument desc = proof is unexpectedly empty; ensure height has not been pruned: invalid request`

**Comment by jtieri** [comment]
This issue is not present in the relayer because we are skipping the code path that resulted in this error.
https://github.com/cosmos/relayer/blob/main/cmd/start.go#L81-L112

Ideally we should fix this or implement a better solution for making sure that when the relayer is running it keeps clients alive by sending a periodic `MsgUpdateClient` to both the src and dst chains for the given path.

**Comment by boojamya** [comment]
Outdated. Closing. 
Updated reference: https://github.com/cosmos/relayer/issues/853
