### ISSUE TITLE
add `feeGranter` to tx sign for sending the transactions

### ISSUE THREAD

**Issue by gsk967** [cosmos/relayer#598]
In the current version  `chain accounts (chain keys)` needs to maintain some balance to pay the `tx fee`

Proposal:
## add two feilds to `chain` 
```go
type Chain struct {
...
  FeeGranterAddress string  `yaml:"fee_granter_address" json:"fee_granter_address"`
  FeeGranted        bool    `yaml:"fee_granted" json:"fee_granted"`
...
}
```
> Set the `feeGranter` address to tx builder  before sign the message while broadcast the message 
```go
if c.FeeGranted {
  feeGrantAddress, err := sdk.AccAddressFromBech32(c.FeeGranterAddress)
  if err != nil {
	  return nil, false, err
  }
  txb.SetFeeGranter(feeGrantAddress)
}
```

**Comment by boojamya** [comment]
Lets sketch this out and brainstorm a proper flow.

**Comment by KyleMoser** [comment]
Relayer needs to pay TX fees in order to submit TXs on chain. Today, this necessitates maintaining balances for multiple accounts (e.g. one funded relayer account per chain). We plan to use a fee grant to allow fees to be used from a central account. I would suggest using a BasicFeeAllowance restricted by a AllowedMsgAllowance so that it only works for certain message types. BasicFeeAllowance can be used in a non-restrictive way so that you basically allow the on-chain account to use up all the fees in the feegranter account, with no time restrictions.

**Assumptions**:
- As of now, relayer accounts associated with the configured chains are funded with native tokens (e.g. uosmo on Osmosis). 
- Once fee grants are in place, _there will still need to be an on-chain account_ that is funded with sufficient tokens (e.g. uosmo for Osmosis)

I think the second assumption above opens questions into how those balances will be maintained. This all seems very similar to the "swap and forward" functionality that we discussed pushing off until Osmosis support arrives.

**Comment by KyleMoser** [comment]
Here's the notes from the discussion Joe and I had. 

1) Create a wallet
2) Create an address per chain
3) Create an address per path
4) Fee grant each path-address from the chain-address
5) New paths automatically get new addresses
6) New paths are automatically feegranted

New relayers would use this behavior by default, for migrations "rly keys init" would prompt the operator with info/for choices to make sure they understand what's happening. For example, the operator will be asked to choose to use an existing account for the FeeGrant account.

Keys/mnemonics will be stored in the keyring-backend "test" and the user will only have to manage funds for one wallet per chain which we'll ensure can be listed with a rly command. 

For now, we won't automatically fund these accounts.

**Comment by KyleMoser** [comment]
- Feegranting CLI commands have been manually tested for the relayer and for lens, including updates to the config file, and on-chain feegranting behavior (e.g. authorizing accounts to be allowed to use feegrants)
- Round robin feegrant behavior has been automated for Lens (e.g., send a ton of TXs, make sure fees are coming out of the correct accounts)
- Round robin feegrant behavior automated testing is _in progress_ for the relayer (it should ultimately work the same as lens, but the ibctest and relayer libraries are substantially different, so isn't as simple as a copy/paste of the lens tests)

The commands for feegranting the relayer are as follows:

`rly chains configure feegrant basicallowance juno default --grantees 10
`
and
`rly chains add X
`

The commands for lens are very similar

- Second command will feegrant the CONFIG by default, but does not run any TXs on chain. So you pretty much always have to run the first command to get things to happen on chain.
- TX signing (round robin) is working for Lens. The default behavior for `SendMsg/SendMsgs `whenever there is a "feegrant" configuration in the config (and thus, in the ChainClient), is to use feegranting.

**Comment by KyleMoser** [comment]
Remaining TODO:

- Add mutex for each grantee (signer) address, Andrew's suggestion was to use:
```
type WalletState struct {
  NextAccountSequence uint64
  Mu sync.Mutex
}

var walletStateMap map[string]*WalletState 
```

- Review the PR to Cosmos SDK and make sure it meets standards
- Run a more manual test on testnet - is there a standard way new releases are tested?

**Comment by jonathanpberger** [comment]
Work done, closing ticket.
