### ISSUE TITLE
Feature request: print out tx content if failed to estimate gas

### ISSUE THREAD

**Issue by larry0x** [cosmos/relayer#926]
Currently, if rly fails to estimate gas before broadcasting a tx, it will print out something like this to the console:

```
2022-08-22T00:33:48.111796Z	info	Error building or broadcasting transaction	{"provider_type": "cosmos", "chain_id": "wasm-test-1", "attempt": 1, "max_attempts": 5, "error": "rpc error: code = InvalidArgument desc = invalid connection hop ID: identifier cannot be blank: invalid identifier: invalid request"}
```

Which contains the error trace, but not the tx itself, making it hard to debug. It would be helpful if the tx body can be printed out here as well.

(btw, if anyone knows what could possibly cause "hop ID" to be empty when creating a channel, please also let me know! it happens sometime when registering new interchain accounts, but not always.)

**Comment by jtieri** [comment]
This is a good issue, I agree that the errors returned when attempting to broadcast a tx are generally not the easiest to pick through.

I'm curious, are you running into the empty hop ID error when attempting to test ICA with this? https://github.com/cosmos/interchain-accounts-demo

I didn't used to see this issue but have started to see it intermittently over the last few weeks myself, but haven't quite gotten to the root cause of the issue yet.

**Comment by larry0x** [comment]
> This is a good issue, I agree that the errors returned when attempting to broadcast a tx are generally not the easiest to pick through.
> 
> I'm curious, are you running into the empty hop ID error when attempting to test ICA with this? https://github.com/cosmos/interchain-accounts-demo
> 
> I didn't used to see this issue but have started to see it intermittently over the last few weeks myself, but haven't quite gotten to the root cause of the issue yet.

i'm using [my own implementation](https://github.com/mars-protocol/hub/tree/ica/x/shuttle) of an ICA authorization module, but yes the error happens when registering new ICAs by invoking `icaControllerKeeper.RegisterInterchainAccount`
